In [1]:
# Imports
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.losses import BinaryCrossentropy


from sklearn.datasets import make_classification
from sklearn.metrics import confusion_matrix, classification_report

# Weights Initialization and Metrics


## Contents

In this module, we will learn:
    1. Weights and Biass Initialization
    2. Metrics to Evaluate the Preformance of a Model
    



## Weights Initialization

We should not initialize the weights with zeroes or randomly (without knowing the distribution):

1. If the weights in a network start too small, then the signal shrinks as it passes through each layer until it’s too tiny to be useful.
2. If the weights in a network start too large, then the signal grows as it passes through each layer until it’s too massive to be useful.

Initializers define the way to set the initial random weights of Keras layers. The keyword arguments used for passing initializers to layers depends on the layer. Usually, it is simply `kernel_initializer` and `bias_initializer`

We can use the built-in initialers or define our own. The built-in itializers in the keras library as as follows:
1. RandomNormal class
2. RandomUniform class
3. TruncatedNormal class
4. Zeros class
5. Ones class
6. GlorotNormal class
7. GlorotUniform class
8. HeNormal class
9. HeUniform class
10. Identity class
11. Orthogonal class
12. Constant class
13. VarianceScaling class

In this module, we will study a few of the built-in initilizers. The details of all the [initializers](https://keras.io/api/layers/initializers/) can be found on keras website.

### RandomNormal Class

Let's define a network with only one layer and one neuron. We will initialize using the `RandomNormal` initializer, as shown in the below example:

In [45]:
initializer = tf.keras.initializers.RandomNormal(mean=0.0, stddev=0.05, seed=1)
model = Sequential(name = 'Model') 
model.add(Dense(units = 1,  activation='sigmoid', input_shape=(2,),name='Layer_1',
                      kernel_initializer = initializer))

print('The weights of the Layer 1 are : {}\n\n'.format(model.get_weights()[0]))
print('The bias of the Layer 1 is : {}'.format(model.get_weights()[1]))

The weights of the Layer 1 are : [[ 0.00633252]
 [-0.02465083]]


The bias of the Layer 1 is : [0.]


***
Let's define a network with two layers: layer 1 has four nodes and layer 2 has one neuron. We will initialize using the `RandomNormal` initializer, as shown in the below example:
***

In [46]:
initializer1 = tf.keras.initializers.RandomNormal(mean=0.0, stddev=0.05, seed=18)
initializer2 = tf.keras.initializers.RandomNormal(mean=0.0, stddev=0.05, seed=13)


model = Sequential(name = 'Model') 
model.add(Dense(units = 4,  activation='sigmoid', input_shape=(2,),name='Layer_1',
                      kernel_initializer = initializer1))
model.add(Dense(units = 1,  activation='sigmoid', name='Layer_2',
                      kernel_initializer = initializer2))
print('The weights of the Layer 1 are : \n{}\n'.format(model.get_weights()[0]))
print('The bias of the Layer 1 is : \n{}\n\n'.format(model.get_weights()[1]))
print('The weights of the Layer 2 are : \n{}\n'.format(model.get_weights()[2]))
print('The bias of the Layer 2 is : \n{}'.format(model.get_weights()[3]))

The weights of the Layer 1 are : 
[[ 0.0604134  -0.0541209  -0.0304674  -0.05781521]
 [-0.0275709  -0.04007006 -0.06057356 -0.00229866]]

The bias of the Layer 1 is : 
[0. 0. 0. 0.]


The weights of the Layer 2 are : 
[[-0.01377632]
 [-0.01184669]
 [-0.10030229]
 [-0.02561714]]

The bias of the Layer 2 is : 
[0.]


***
***
### RandomUniform Class

Let's define a network with only one layer and one neuron. We will initialize using the `RandomUniform` initializer, as shown in the below example:

In [47]:
initializer = tf.keras.initializers.RandomUniform(minval=0.,maxval=1., seed=1)
model = Sequential(name = 'Model') 
model.add(Dense(units = 1,  activation='sigmoid', input_shape=(2,),name='Layer_1',
                      kernel_initializer = initializer))

print('The weights of the Layer 1 are : \n{}\n'.format(model.get_weights()[0]))
print('The bias of the Layer 1 is : {}'.format(model.get_weights()[1]))

The weights of the Layer 1 are : 
[[0.8784882 ]
 [0.45998025]]

The bias of the Layer 1 is : [0.]


***
Let's define a network with two layers: layer 1 has four nodes and layer 2 has one neuron. We will initialize using the `RandomNormal` initializer, as shown in the below example:
***

In [48]:
initializer1 = tf.keras.initializers.RandomUniform(minval=0., maxval=1., seed=18)
initializer2 = tf.keras.initializers.RandomUniform(minval=0., maxval=1., seed=13)


model = Sequential(name = 'Model') 
model.add(Dense(units = 4,  activation='sigmoid', input_shape=(2,),name='Layer_1',
                      kernel_initializer = initializer1))
model.add(Dense(units = 1,  activation='sigmoid', name='Layer_2',
                      kernel_initializer = initializer2))
print('The weights of the Layer 1 are : \n{}\n'.format(model.get_weights()[0]))
print('The bias of the Layer 1 is : \n{}\n\n'.format(model.get_weights()[1]))
print('The weights of the Layer 2 are : \n{}\n'.format(model.get_weights()[2]))
print('The bias of the Layer 2 is : \n{}'.format(model.get_weights()[3]))

The weights of the Layer 1 are : 
[[0.26826763 0.36626482 0.42563546 0.5771897 ]
 [0.62303483 0.5959183  0.47955918 0.74396324]]

The bias of the Layer 1 is : 
[0. 0. 0. 0.]


The weights of the Layer 2 are : 
[[0.9361063 ]
 [0.6369631 ]
 [0.11726046]
 [0.7102027 ]]

The bias of the Layer 2 is : 
[0.]


***
***
### Zero Class
Let's define a network with only one layer and one neuron. We will initialize using the `Zeros` initializer, as shown in the below example:

In [49]:
initializer = tf.keras.initializers.Zeros()
model = Sequential(name = 'Model') 
model.add(Dense(units = 1,  activation='sigmoid', input_shape=(2,),name='Layer_1',
                      kernel_initializer = initializer))

print('The weights of the Layer 1 are : \n{}\n'.format(model.get_weights()[0]))
print('The bias of the Layer 1 is : {}'.format(model.get_weights()[1]))

The weights of the Layer 1 are : 
[[0.]
 [0.]]

The bias of the Layer 1 is : [0.]


***
Let's define a network with two layers: layer 1 has four nodes and layer 2 has one neuron. We will initialize using the `Zeros` initializer, as shown in the below example:
***

In [52]:
initializer = tf.keras.initializers.Zeros()


model = Sequential(name = 'Model') 
model.add(Dense(units = 4,  activation='sigmoid', input_shape=(2,),name='Layer_1',
                      kernel_initializer = initializer))
model.add(Dense(units = 1,  activation='sigmoid', name='Layer_2',
                      kernel_initializer = initializer))
print('The weights of the Layer 1 are : \n{}\n'.format(model.get_weights()[0]))
print('The bias of the Layer 1 is : \n{}\n\n'.format(model.get_weights()[1]))
print('The weights of the Layer 2 are : \n{}\n'.format(model.get_weights()[2]))
print('The bias of the Layer 2 is : \n{}'.format(model.get_weights()[3]))

The weights of the Layer 1 are : 
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]

The bias of the Layer 1 is : 
[0. 0. 0. 0.]


The weights of the Layer 2 are : 
[[0.]
 [0.]
 [0.]
 [0.]]

The bias of the Layer 2 is : 
[0.]


***
***
### Ones Class
Let's define a network with only one layer and one neuron. We will initialize using the `Ones` initializer, as shown in the below example:

In [53]:
initializer = tf.keras.initializers.Ones()
model = Sequential(name = 'Model') 
model.add(Dense(units = 1,  activation='sigmoid', input_shape=(2,),name='Layer_1',
                      kernel_initializer = initializer))

print('The weights of the Layer 1 are : \n{}\n'.format(model.get_weights()[0]))
print('The bias of the Layer 1 is : {}'.format(model.get_weights()[1]))

The weights of the Layer 1 are : 
[[1.]
 [1.]]

The bias of the Layer 1 is : [0.]


***
Let's define a network with two layers: layer 1 has four nodes and layer 2 has one neuron. We will initialize using the `Ones` initializer, as shown in the below example:
***

In [54]:
initializer1 = tf.keras.initializers.Ones()


model = Sequential(name = 'Model') 
model.add(Dense(units = 4,  activation='sigmoid', input_shape=(2,),name='Layer_1',
                      kernel_initializer = initializer,
               bias_initializer = initializer))
model.add(Dense(units = 1,  activation='sigmoid', name='Layer_2',
                      kernel_initializer = initializer))
print('The weights of the Layer 1 are : \n{}\n'.format(model.get_weights()[0]))
print('The bias of the Layer 1 is : \n{}\n\n'.format(model.get_weights()[1]))
print('The weights of the Layer 2 are : \n{}\n'.format(model.get_weights()[2]))
print('The bias of the Layer 2 is : \n{}'.format(model.get_weights()[3]))

The weights of the Layer 1 are : 
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]

The bias of the Layer 1 is : 
[1. 1. 1. 1.]


The weights of the Layer 2 are : 
[[1.]
 [1.]
 [1.]
 [1.]]

The bias of the Layer 2 is : 
[0.]


***
***
### GlorotNormal Class

The Glorot normal initializer, also called Xavier normal initializer, can be initialzed using `tf.keras.initializers.glorot_normal`.

Xavier Initialization initializes the weights in a network by drawing them from truncated normal distribution centered on 0 with the following standard deviation

\begin{equation}
stddev = \sqrt{\frac{2}{f_{an\_in}+f_{an\_out}}}
\end{equation}

where $f_{an\_in}$ and $f_{an\_out}$ is the number of input neurons and the number of output neurons, respectively, in weight tensors.




Let's define a network with only one layer and one neuron. We will initialize using the `RandomUniform` initializer, as shown in the below example:

In [56]:
initializer = tf.keras.initializers.GlorotNormal(seed = 1)
model = Sequential(name = 'Model') 
model.add(Dense(units = 1,  activation='sigmoid', input_shape=(2,),name='Layer_1',
                      kernel_initializer = initializer))

print('The weights of the Layer 1 are : \n{}\n'.format(model.get_weights()[0]))
print('The bias of the Layer 1 is : {}'.format(model.get_weights()[1]))

The weights of the Layer 1 are : 
[[ 0.11756085]
 [-0.4576337 ]]

The bias of the Layer 1 is : [0.]


***
Let's define a network with two layers: layer 1 has four nodes and layer 2 has one neuron. We will initialize using the `GlorotNormal` initializer, as shown in the below example:
***

In [57]:
initializer1 = tf.keras.initializers.GlorotNormal( seed=18)
initializer2 = tf.keras.initializers.GlorotNormal(seed = 13)


model = Sequential(name = 'Model') 
model.add(Dense(units = 4,  activation='sigmoid', input_shape=(2,),name='Layer_1',
                      kernel_initializer = initializer1))
model.add(Dense(units = 1,  activation='sigmoid', name='Layer_2',
                      kernel_initializer = initializer2))
print('The weights of the Layer 1 are : \n{}\n'.format(model.get_weights()[0]))
print('The bias of the Layer 1 is : \n{}\n\n'.format(model.get_weights()[1]))
print('The weights of the Layer 2 are : \n{}\n'.format(model.get_weights()[2]))
print('The bias of the Layer 2 is : \n{}'.format(model.get_weights()[3]))

The weights of the Layer 1 are : 
[[ 0.7930576  -0.7104549  -0.39995104 -0.7589507 ]
 [ 0.28310135 -0.3424158   0.20694703 -0.23174384]]

The bias of the Layer 1 is : 
[0. 0. 0. 0.]


The weights of the Layer 2 are : 
[[-0.19810493]
 [-0.17035674]
 [-0.36837715]
 [-0.37561056]]

The bias of the Layer 2 is : 
[0.]


***
***
### GlorotUniform class

The Glorot uniform initializer, also called Xavier uniform initializer, is initialized using `tf.keras.initializers.glorot_uniform`.

It draws samples from a uniform distribution within $[-limit, limit]$, where 
\begin{equation}
limit = \sqrt{\frac{6}{f_{an\_in} + f_{an\_out}}}
\end{equation}

where $f_{an\_in}$ is the number of input units in the weight tensor and $f_{an\_out}$ is the number of output units).



Let's define a network with only one layer and one neuron. We will initialize using the `GlorotUniform` initializer, as shown in the below example:

In [58]:
initializer = tf.keras.initializers.GlorotUniform(seed=1)
model = Sequential(name = 'Model') 
model.add(Dense(units = 1,  activation='sigmoid', input_shape=(2,),name='Layer_1',
                      kernel_initializer = initializer))

print('The weights of the Layer 1 are : \n{}\n'.format(model.get_weights()[0]))
print('The bias of the Layer 1 is : {}'.format(model.get_weights()[1]))

The weights of the Layer 1 are : 
[[ 1.0705262 ]
 [-0.11319292]]

The bias of the Layer 1 is : [0.]


***
Let's define a network with two layers: layer 1 has four nodes and layer 2 has one neuron. We will initialize using the `GlorotUniform` initializer, as shown in the below example:
***

In [59]:
initializer1 = tf.keras.initializers.GlorotUniform(seed=18)
initializer2 = tf.keras.initializers.GlorotUniform(seed=13)


model = Sequential(name = 'Model') 
model.add(Dense(units = 4,  activation='sigmoid', input_shape=(2,),name='Layer_1',
                      kernel_initializer = initializer1))
model.add(Dense(units = 1,  activation='sigmoid', name='Layer_2',
                      kernel_initializer = initializer2))
print('The weights of the Layer 1 are : \n{}\n'.format(model.get_weights()[0]))
print('The bias of the Layer 1 is : \n{}\n\n'.format(model.get_weights()[1]))
print('The weights of the Layer 2 are : \n{}\n'.format(model.get_weights()[2]))
print('The bias of the Layer 2 is : \n{}'.format(model.get_weights()[3]))

The weights of the Layer 1 are : 
[[-0.46346474 -0.26747036 -0.14872909  0.15437937]
 [ 0.24606967  0.1918366  -0.04088163  0.48792648]]

The bias of the Layer 1 is : 
[0. 0. 0. 0.]


The weights of the Layer 2 are : 
[[ 0.955461  ]
 [ 0.30007124]
 [-0.8385403 ]
 [ 0.460531  ]]

The bias of the Layer 2 is : 
[0.]


In [ ]:
***
***
### Zero Class
Let's define a network with only one layer and one neuron. We will initialize using the `RandomUniform` initializer, as shown in the below example:

In [ ]:
initializer = tf.keras.initializers.RandomUniform(minval=0.,maxval=1., seed=1)
model = Sequential(name = 'Model') 
model.add(Dense(units = 1,  activation='sigmoid', input_shape=(2,),name='Layer_1',
                      kernel_initializer = initializer))

print('The weights of the Layer 1 are : \n{}\n'.format(model.get_weights()[0]))
print('The bias of the Layer 1 is : {}'.format(model.get_weights()[1]))

In [ ]:
***
Let's define a network with two layers: layer 1 has four nodes and layer 2 has one neuron. We will initialize using the `RandomNormal` initializer, as shown in the below example:
***

In [ ]:
initializer1 = tf.keras.initializers.RandomUniform(minval=0., maxval=1., seed=18)
initializer2 = tf.keras.initializers.RandomUniform(minval=0., maxval=1., seed=13)


model = Sequential(name = 'Model') 
model.add(Dense(units = 4,  activation='sigmoid', input_shape=(2,),name='Layer_1',
                      kernel_initializer = initializer1))
model.add(Dense(units = 1,  activation='sigmoid', name='Layer_2',
                      kernel_initializer = initializer2))
print('The weights of the Layer 1 are : \n{}\n'.format(model.get_weights()[0]))
print('The bias of the Layer 1 is : \n{}\n\n'.format(model.get_weights()[1]))
print('The weights of the Layer 2 are : \n{}\n'.format(model.get_weights()[2]))
print('The bias of the Layer 2 is : \n{}'.format(model.get_weights()[3]))

In [ ]:
***
***
### Zero Class
Let's define a network with only one layer and one neuron. We will initialize using the `RandomUniform` initializer, as shown in the below example:

In [ ]:
initializer = tf.keras.initializers.RandomUniform(minval=0.,maxval=1., seed=1)
model = Sequential(name = 'Model') 
model.add(Dense(units = 1,  activation='sigmoid', input_shape=(2,),name='Layer_1',
                      kernel_initializer = initializer))

print('The weights of the Layer 1 are : \n{}\n'.format(model.get_weights()[0]))
print('The bias of the Layer 1 is : {}'.format(model.get_weights()[1]))

In [ ]:
***
Let's define a network with two layers: layer 1 has four nodes and layer 2 has one neuron. We will initialize using the `RandomNormal` initializer, as shown in the below example:
***

In [ ]:
initializer1 = tf.keras.initializers.RandomUniform(minval=0., maxval=1., seed=18)
initializer2 = tf.keras.initializers.RandomUniform(minval=0., maxval=1., seed=13)


model = Sequential(name = 'Model') 
model.add(Dense(units = 4,  activation='sigmoid', input_shape=(2,),name='Layer_1',
                      kernel_initializer = initializer1))
model.add(Dense(units = 1,  activation='sigmoid', name='Layer_2',
                      kernel_initializer = initializer2))
print('The weights of the Layer 1 are : \n{}\n'.format(model.get_weights()[0]))
print('The bias of the Layer 1 is : \n{}\n\n'.format(model.get_weights()[1]))
print('The weights of the Layer 2 are : \n{}\n'.format(model.get_weights()[2]))
print('The bias of the Layer 2 is : \n{}'.format(model.get_weights()[3]))

# References

1. [Xavier and He Normal Initialization](https://prateekvishnu.medium.com/xavier-and-he-normal-he-et-al-initialization-8e3d7a087528)
2. [Weights and Biases Initialization](https://keras.io/api/layers/initializers/#glorotnormal-class)