In [1]:
# Imports
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.losses import BinaryCrossentropy


from sklearn.datasets import make_classification
from sklearn.metrics import confusion_matrix, classification_report

# Weights Initialization and Metrics


## Contents

In this module, we will learn:
    1. Weights and Biass Initialization
    2. Metrics to Evaluate the Preformance of a Model
    



## Weights Initialization


Initializers define the way to set the initial random weights of Keras layers. The keyword arguments used for passing initializers to layers depends on the layer. Usually, it is simply `kernel_initializer` and `bias_initializer`

We can use the built-in initialers or define our own. The built-in itializers in the keras library as as follows:
1. RandomNormal class
2. RandomUniform class
3. TruncatedNormal class
4. Zeros class
5. Ones class
6. GlorotNormal class
7. GlorotUniform class
8. HeNormal class
9. HeUniform class
10. Identity class
11. Orthogonal class
12. Constant class
13. VarianceScaling class

In this module, we will study a few of the built-in initilizers. The details of all the [initializers](https://keras.io/api/layers/initializers/) can be found on keras website.

### RandomNormal Class

Let's define a network with only one layer and one neuron. We will initialize using the `RandomNormal` initializer, as shown in the below example:

In [45]:
initializer = tf.keras.initializers.RandomNormal(mean=0.0, stddev=0.05, seed=1)
model = Sequential(name = 'Model') 
model.add(Dense(units = 1,  activation='sigmoid', input_shape=(2,),name='Layer_1',
                      kernel_initializer = initializer))

print('The weights of the Layer 1 are : {}\n\n'.format(model.get_weights()[0]))
print('The bias of the Layer 1 is : {}'.format(model.get_weights()[1]))

The weights of the Layer 1 are : [[ 0.00633252]
 [-0.02465083]]


The bias of the Layer 1 is : [0.]


***
Let's define a network with two layers: layer 1 has four nodes and layer 2 has one neuron. We will initialize using the `RandomNormal` initializer, as shown in the below example:
***

In [46]:
initializer1 = tf.keras.initializers.RandomNormal(mean=0.0, stddev=0.05, seed=18)
initializer2 = tf.keras.initializers.RandomNormal(mean=0.0, stddev=0.05, seed=13)


model = Sequential(name = 'Model') 
model.add(Dense(units = 4,  activation='sigmoid', input_shape=(2,),name='Layer_1',
                      kernel_initializer = initializer1))
model.add(Dense(units = 1,  activation='sigmoid', name='Layer_2',
                      kernel_initializer = initializer2))
print('The weights of the Layer 1 are : \n{}\n'.format(model.get_weights()[0]))
print('The bias of the Layer 1 is : \n{}\n\n'.format(model.get_weights()[1]))
print('The weights of the Layer 2 are : \n{}\n'.format(model.get_weights()[2]))
print('The bias of the Layer 2 is : \n{}'.format(model.get_weights()[3]))

The weights of the Layer 1 are : 
[[ 0.0604134  -0.0541209  -0.0304674  -0.05781521]
 [-0.0275709  -0.04007006 -0.06057356 -0.00229866]]

The bias of the Layer 1 is : 
[0. 0. 0. 0.]


The weights of the Layer 2 are : 
[[-0.01377632]
 [-0.01184669]
 [-0.10030229]
 [-0.02561714]]

The bias of the Layer 2 is : 
[0.]


***
***
### RandomUniform Class

Let's define a network with only one layer and one neuron. We will initialize using the `RandomUniform` initializer, as shown in the below example:

In [47]:
initializer = tf.keras.initializers.RandomUniform(minval=0.,maxval=1., seed=1)
model = Sequential(name = 'Model') 
model.add(Dense(units = 1,  activation='sigmoid', input_shape=(2,),name='Layer_1',
                      kernel_initializer = initializer))

print('The weights of the Layer 1 are : \n{}\n'.format(model.get_weights()[0]))
print('The bias of the Layer 1 is : {}'.format(model.get_weights()[1]))

The weights of the Layer 1 are : 
[[0.8784882 ]
 [0.45998025]]

The bias of the Layer 1 is : [0.]


***
Let's define a network with two layers: layer 1 has four nodes and layer 2 has one neuron. We will initialize using the `RandomNormal` initializer, as shown in the below example:
***

In [48]:
initializer1 = tf.keras.initializers.RandomUniform(minval=0., maxval=1., seed=18)
initializer2 = tf.keras.initializers.RandomUniform(minval=0., maxval=1., seed=13)


model = Sequential(name = 'Model') 
model.add(Dense(units = 4,  activation='sigmoid', input_shape=(2,),name='Layer_1',
                      kernel_initializer = initializer1))
model.add(Dense(units = 1,  activation='sigmoid', name='Layer_2',
                      kernel_initializer = initializer2))
print('The weights of the Layer 1 are : \n{}\n'.format(model.get_weights()[0]))
print('The bias of the Layer 1 is : \n{}\n\n'.format(model.get_weights()[1]))
print('The weights of the Layer 2 are : \n{}\n'.format(model.get_weights()[2]))
print('The bias of the Layer 2 is : \n{}'.format(model.get_weights()[3]))

The weights of the Layer 1 are : 
[[0.26826763 0.36626482 0.42563546 0.5771897 ]
 [0.62303483 0.5959183  0.47955918 0.74396324]]

The bias of the Layer 1 is : 
[0. 0. 0. 0.]


The weights of the Layer 2 are : 
[[0.9361063 ]
 [0.6369631 ]
 [0.11726046]
 [0.7102027 ]]

The bias of the Layer 2 is : 
[0.]


***
***
### Zero Class
Let's define a network with only one layer and one neuron. We will initialize using the `Zeros` initializer, as shown in the below example:

In [49]:
initializer = tf.keras.initializers.Zeros()
model = Sequential(name = 'Model') 
model.add(Dense(units = 1,  activation='sigmoid', input_shape=(2,),name='Layer_1',
                      kernel_initializer = initializer))

print('The weights of the Layer 1 are : \n{}\n'.format(model.get_weights()[0]))
print('The bias of the Layer 1 is : {}'.format(model.get_weights()[1]))

The weights of the Layer 1 are : 
[[0.]
 [0.]]

The bias of the Layer 1 is : [0.]


***
Let's define a network with two layers: layer 1 has four nodes and layer 2 has one neuron. We will initialize using the `Zeros` initializer, as shown in the below example:
***

In [52]:
initializer = tf.keras.initializers.Zeros()


model = Sequential(name = 'Model') 
model.add(Dense(units = 4,  activation='sigmoid', input_shape=(2,),name='Layer_1',
                      kernel_initializer = initializer))
model.add(Dense(units = 1,  activation='sigmoid', name='Layer_2',
                      kernel_initializer = initializer))
print('The weights of the Layer 1 are : \n{}\n'.format(model.get_weights()[0]))
print('The bias of the Layer 1 is : \n{}\n\n'.format(model.get_weights()[1]))
print('The weights of the Layer 2 are : \n{}\n'.format(model.get_weights()[2]))
print('The bias of the Layer 2 is : \n{}'.format(model.get_weights()[3]))

The weights of the Layer 1 are : 
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]

The bias of the Layer 1 is : 
[0. 0. 0. 0.]


The weights of the Layer 2 are : 
[[0.]
 [0.]
 [0.]
 [0.]]

The bias of the Layer 2 is : 
[0.]


***
***
### Ones Class
Let's define a network with only one layer and one neuron. We will initialize using the `Ones` initializer, as shown in the below example:

In [53]:
initializer = tf.keras.initializers.Ones()
model = Sequential(name = 'Model') 
model.add(Dense(units = 1,  activation='sigmoid', input_shape=(2,),name='Layer_1',
                      kernel_initializer = initializer))

print('The weights of the Layer 1 are : \n{}\n'.format(model.get_weights()[0]))
print('The bias of the Layer 1 is : {}'.format(model.get_weights()[1]))

The weights of the Layer 1 are : 
[[1.]
 [1.]]

The bias of the Layer 1 is : [0.]


***
Let's define a network with two layers: layer 1 has four nodes and layer 2 has one neuron. We will initialize using the `Ones` initializer, as shown in the below example:
***

In [54]:
initializer1 = tf.keras.initializers.Ones()


model = Sequential(name = 'Model') 
model.add(Dense(units = 4,  activation='sigmoid', input_shape=(2,),name='Layer_1',
                      kernel_initializer = initializer,
               bias_initializer = initializer))
model.add(Dense(units = 1,  activation='sigmoid', name='Layer_2',
                      kernel_initializer = initializer))
print('The weights of the Layer 1 are : \n{}\n'.format(model.get_weights()[0]))
print('The bias of the Layer 1 is : \n{}\n\n'.format(model.get_weights()[1]))
print('The weights of the Layer 2 are : \n{}\n'.format(model.get_weights()[2]))
print('The bias of the Layer 2 is : \n{}'.format(model.get_weights()[3]))

The weights of the Layer 1 are : 
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]

The bias of the Layer 1 is : 
[1. 1. 1. 1.]


The weights of the Layer 2 are : 
[[1.]
 [1.]
 [1.]
 [1.]]

The bias of the Layer 2 is : 
[0.]


In [ ]:
***
***
### Zero Class
Let's define a network with only one layer and one neuron. We will initialize using the `RandomUniform` initializer, as shown in the below example:

In [ ]:
initializer = tf.keras.initializers.RandomUniform(minval=0.,maxval=1., seed=1)
model = Sequential(name = 'Model') 
model.add(Dense(units = 1,  activation='sigmoid', input_shape=(2,),name='Layer_1',
                      kernel_initializer = initializer))

print('The weights of the Layer 1 are : \n{}\n'.format(model.get_weights()[0]))
print('The bias of the Layer 1 is : {}'.format(model.get_weights()[1]))

In [ ]:
***
Let's define a network with two layers: layer 1 has four nodes and layer 2 has one neuron. We will initialize using the `RandomNormal` initializer, as shown in the below example:
***

In [ ]:
initializer1 = tf.keras.initializers.RandomUniform(minval=0., maxval=1., seed=18)
initializer2 = tf.keras.initializers.RandomUniform(minval=0., maxval=1., seed=13)


model = Sequential(name = 'Model') 
model.add(Dense(units = 4,  activation='sigmoid', input_shape=(2,),name='Layer_1',
                      kernel_initializer = initializer1))
model.add(Dense(units = 1,  activation='sigmoid', name='Layer_2',
                      kernel_initializer = initializer2))
print('The weights of the Layer 1 are : \n{}\n'.format(model.get_weights()[0]))
print('The bias of the Layer 1 is : \n{}\n\n'.format(model.get_weights()[1]))
print('The weights of the Layer 2 are : \n{}\n'.format(model.get_weights()[2]))
print('The bias of the Layer 2 is : \n{}'.format(model.get_weights()[3]))

In [ ]:
***
***
### Zero Class
Let's define a network with only one layer and one neuron. We will initialize using the `RandomUniform` initializer, as shown in the below example:

In [ ]:
initializer = tf.keras.initializers.RandomUniform(minval=0.,maxval=1., seed=1)
model = Sequential(name = 'Model') 
model.add(Dense(units = 1,  activation='sigmoid', input_shape=(2,),name='Layer_1',
                      kernel_initializer = initializer))

print('The weights of the Layer 1 are : \n{}\n'.format(model.get_weights()[0]))
print('The bias of the Layer 1 is : {}'.format(model.get_weights()[1]))

In [ ]:
***
Let's define a network with two layers: layer 1 has four nodes and layer 2 has one neuron. We will initialize using the `RandomNormal` initializer, as shown in the below example:
***

In [ ]:
initializer1 = tf.keras.initializers.RandomUniform(minval=0., maxval=1., seed=18)
initializer2 = tf.keras.initializers.RandomUniform(minval=0., maxval=1., seed=13)


model = Sequential(name = 'Model') 
model.add(Dense(units = 4,  activation='sigmoid', input_shape=(2,),name='Layer_1',
                      kernel_initializer = initializer1))
model.add(Dense(units = 1,  activation='sigmoid', name='Layer_2',
                      kernel_initializer = initializer2))
print('The weights of the Layer 1 are : \n{}\n'.format(model.get_weights()[0]))
print('The bias of the Layer 1 is : \n{}\n\n'.format(model.get_weights()[1]))
print('The weights of the Layer 2 are : \n{}\n'.format(model.get_weights()[2]))
print('The bias of the Layer 2 is : \n{}'.format(model.get_weights()[3]))

In [ ]:
***
***
### Zero Class
Let's define a network with only one layer and one neuron. We will initialize using the `RandomUniform` initializer, as shown in the below example:

In [ ]:
initializer = tf.keras.initializers.RandomUniform(minval=0.,maxval=1., seed=1)
model = Sequential(name = 'Model') 
model.add(Dense(units = 1,  activation='sigmoid', input_shape=(2,),name='Layer_1',
                      kernel_initializer = initializer))

print('The weights of the Layer 1 are : \n{}\n'.format(model.get_weights()[0]))
print('The bias of the Layer 1 is : {}'.format(model.get_weights()[1]))

In [ ]:
***
Let's define a network with two layers: layer 1 has four nodes and layer 2 has one neuron. We will initialize using the `RandomNormal` initializer, as shown in the below example:
***

In [ ]:
initializer1 = tf.keras.initializers.RandomUniform(minval=0., maxval=1., seed=18)
initializer2 = tf.keras.initializers.RandomUniform(minval=0., maxval=1., seed=13)


model = Sequential(name = 'Model') 
model.add(Dense(units = 4,  activation='sigmoid', input_shape=(2,),name='Layer_1',
                      kernel_initializer = initializer1))
model.add(Dense(units = 1,  activation='sigmoid', name='Layer_2',
                      kernel_initializer = initializer2))
print('The weights of the Layer 1 are : \n{}\n'.format(model.get_weights()[0]))
print('The bias of the Layer 1 is : \n{}\n\n'.format(model.get_weights()[1]))
print('The weights of the Layer 2 are : \n{}\n'.format(model.get_weights()[2]))
print('The bias of the Layer 2 is : \n{}'.format(model.get_weights()[3]))

In [ ]:
***
***
### Zero Class
Let's define a network with only one layer and one neuron. We will initialize using the `RandomUniform` initializer, as shown in the below example:

In [ ]:
initializer = tf.keras.initializers.RandomUniform(minval=0.,maxval=1., seed=1)
model = Sequential(name = 'Model') 
model.add(Dense(units = 1,  activation='sigmoid', input_shape=(2,),name='Layer_1',
                      kernel_initializer = initializer))

print('The weights of the Layer 1 are : \n{}\n'.format(model.get_weights()[0]))
print('The bias of the Layer 1 is : {}'.format(model.get_weights()[1]))

In [ ]:
***
Let's define a network with two layers: layer 1 has four nodes and layer 2 has one neuron. We will initialize using the `RandomNormal` initializer, as shown in the below example:
***

In [ ]:
initializer1 = tf.keras.initializers.RandomUniform(minval=0., maxval=1., seed=18)
initializer2 = tf.keras.initializers.RandomUniform(minval=0., maxval=1., seed=13)


model = Sequential(name = 'Model') 
model.add(Dense(units = 4,  activation='sigmoid', input_shape=(2,),name='Layer_1',
                      kernel_initializer = initializer1))
model.add(Dense(units = 1,  activation='sigmoid', name='Layer_2',
                      kernel_initializer = initializer2))
print('The weights of the Layer 1 are : \n{}\n'.format(model.get_weights()[0]))
print('The bias of the Layer 1 is : \n{}\n\n'.format(model.get_weights()[1]))
print('The weights of the Layer 2 are : \n{}\n'.format(model.get_weights()[2]))
print('The bias of the Layer 2 is : \n{}'.format(model.get_weights()[3]))